AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:

  EventMan:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: eventAuth
        Authorizers:
          eventAuth:
            UserPoolArn: arn:aws:cognito-idp:eu-central-1:845376454911:userpool/eu-central-1_l19y1ueM5

  EventTesterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Lambda/
      Handler: Lambda::Lambda.EventHandler::EventTesterHandler
      Runtime: dotnetcore3.1
      Role: arn:aws:iam::845376454911:role/service-role/MessageScan-role-av1nmp7k
      Timeout: 30
      Events:
        EventTester:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref EventMan
            Path: /eventTester
            Method: get

  CreateEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Lambda/
      Handler: Lambda::Lambda.EventHandler::CreateEvent
      Runtime: dotnetcore3.1
      Role: arn:aws:iam::845376454911:role/service-role/MessageScan-role-av1nmp7k
      Timeout: 30
      Events:
        EventTester:
          Type: Api
          Properties:
            RestApiId: !Ref EventMan
            Path: /event
            Method: post

  GetEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Lambda/
      Handler: Lambda::Lambda.EventHandler::GetEvents
      Runtime: dotnetcore3.1
      Role: arn:aws:iam::845376454911:role/service-role/MessageScan-role-av1nmp7k
      Timeout: 30
      Events:
        EventTester:
          Type: Api
          Properties:
            RestApiId: !Ref EventMan
            Path: /event
            Method: get

  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Lambda/
      Handler: Lambda::Lambda.UserHandler::CreateUser
      Runtime: dotnetcore3.1
      Role: arn:aws:iam::845376454911:role/service-role/MessageScan-role-av1nmp7k
      Timeout: 30
      Events:
        EventTester:
          Type: Api
          Properties:
            RestApiId: !Ref EventMan
            Path: /user
            Method: post

  UserSignUpForEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Lambda/
      Handler: Lambda::Lambda.EventHandler::UserSignUpForEvent
      Runtime: dotnetcore3.1
      Role: arn:aws:iam::845376454911:role/service-role/MessageScan-role-av1nmp7k
      Timeout: 30
      Events:
        EventTester:
          Type: Api
          Properties:
            RestApiId: !Ref EventMan
            Path: /userSignUp
            Method: post

  GetUserSignUpsForEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Lambda/
      Handler: Lambda::Lambda.EventHandler::GetUserSignUpsForEvent
      Runtime: dotnetcore3.1
      Role: arn:aws:iam::845376454911:role/service-role/MessageScan-role-av1nmp7k
      Timeout: 30
      Events:
        EventTester:
          Type: Api
          Properties:
            RestApiId: !Ref EventMan
            Path: /userSignUp/{id}
            Method: get

  EventDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EventDB
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: skgsi
          AttributeType: S
        - AttributeName: data
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: skgsi
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: skgsi-data-index
          KeySchema:
            - AttributeName: skgsi
              KeyType: HASH
            - AttributeName: data
              KeyType: RANGE
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
